// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: sort_grpc.proto

package sort_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SortRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Array []int32 `protobuf:"varint,1,rep,packed,name=array,proto3" json:"array,omitempty"`
}

func (x *SortRequest) Reset() {
	*x = SortRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sort_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortRequest) ProtoMessage() {}

func (x *SortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sort_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortRequest.ProtoReflect.Descriptor instead.
func (*SortRequest) Descriptor() ([]byte, []int) {
	return file_sort_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *SortRequest) GetArray() []int32 {
	if x != nil {
		return x.Array
	}
	return nil
}

type SortResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SortedArray []int32 `protobuf:"varint,1,rep,packed,name=sortedArray,proto3" json:"sortedArray,omitempty"`
}

func (x *SortResponse) Reset() {
	*x = SortResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sort_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortResponse) ProtoMessage() {}

func (x *SortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sort_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortResponse.ProtoReflect.Descriptor instead.
func (*SortResponse) Descriptor() ([]byte, []int) {
	return file_sort_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *SortResponse) GetSortedArray() []int32 {
	if x != nil {
		return x.SortedArray
	}
	return nil
}

var File_sort_grpc_proto protoreflect.FileDescriptor

var file_sort_grpc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x22, 0x23, 0x0a, 0x0b,
	0x53, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x72, 0x72, 0x61, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x61, 0x72, 0x72, 0x61,
	0x79, 0x22, 0x30, 0x0a, 0x0c, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x41, 0x72, 0x72, 0x61, 0x79,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x41, 0x72,
	0x72, 0x61, 0x79, 0x32, 0x8d, 0x01, 0x0a, 0x0b, 0x53, 0x6f, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x53, 0x6f, 0x72, 0x74,
	0x12, 0x16, 0x2e, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x6f, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x73, 0x6f, 0x72, 0x74, 0x5f,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x09, 0x51, 0x75, 0x69, 0x63, 0x6b, 0x53, 0x6f, 0x72, 0x74,
	0x12, 0x16, 0x2e, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x6f, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x73, 0x6f, 0x72, 0x74, 0x5f,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x3b, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x67, 0x72,
	0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sort_grpc_proto_rawDescOnce sync.Once
	file_sort_grpc_proto_rawDescData = file_sort_grpc_proto_rawDesc
)

func file_sort_grpc_proto_rawDescGZIP() []byte {
	file_sort_grpc_proto_rawDescOnce.Do(func() {
		file_sort_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_sort_grpc_proto_rawDescData)
	})
	return file_sort_grpc_proto_rawDescData
}

var file_sort_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sort_grpc_proto_goTypes = []any{
	(*SortRequest)(nil),  // 0: sort_grpc.SortRequest
	(*SortResponse)(nil), // 1: sort_grpc.SortResponse
}
var file_sort_grpc_proto_depIdxs = []int32{
	0, // 0: sort_grpc.SortService.MergeSort:input_type -> sort_grpc.SortRequest
	0, // 1: sort_grpc.SortService.QuickSort:input_type -> sort_grpc.SortRequest
	1, // 2: sort_grpc.SortService.MergeSort:output_type -> sort_grpc.SortResponse
	1, // 3: sort_grpc.SortService.QuickSort:output_type -> sort_grpc.SortResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sort_grpc_proto_init() }
func file_sort_grpc_proto_init() {
	if File_sort_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sort_grpc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SortRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sort_grpc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SortResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sort_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sort_grpc_proto_goTypes,
		DependencyIndexes: file_sort_grpc_proto_depIdxs,
		MessageInfos:      file_sort_grpc_proto_msgTypes,
	}.Build()
	File_sort_grpc_proto = out.File
	file_sort_grpc_proto_rawDesc = nil
	file_sort_grpc_proto_goTypes = nil
	file_sort_grpc_proto_depIdxs = nil
}
